backend:
  name: git-gateway
  branch: main

media_folder: src/assets/images
public_folder: /images
site_url: https://caracals.de
locale: de
logo_url: /images/admin-logo.svg

collections:
  - name: team
    label: Team
    folder: src/pages/teams
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: featuredImage, widget: image }
      - label: Introduction
        name: introduction
        widget: object
        fields:
          - { label: Title, name: intro-title, widget: string }
          - { label: Text, name: intro-text, widget: markdown }
      - label: Gallery
        name: gallery
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Caption, name: caption, widget: string }
      - label: Content
        name: main
        widget: object
        fields:
          - label: Title
            name: title
            widget: string
          - label: Text
            name: text
            widget: markdown
  - name: page
    label: Page
    files:
      - label: Training
        file: src/pages/training.md
        name: training
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: Content, name: body, widget: markdown }
  - name: content
    label: Content
    files:
    - label: Home
      file: src/content/pages/index.md
      name: index
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Hero Image, name: heroImage, widget: image }
        - { label: Intro, name: intro, widget: markdown }
        - label: Teams
          name: teams
          widget: list
          identifier_field: name
          fields:
            - { label: Title, name: name, widget: string }
            - { label: URL-Handle, name: handle, widget: string }
            - { label: Image, name: image, widget: image }
        - label: About
          name: about
          widget: object
          fields:
            - label: Image
              name: image
              widget: image
            - label: Title
              name: title
              widget: string
            - label: Title
              name: text
              widget: markdown
        - label: Links
          name: links
          widget: list
          identifier_field: label
          fields:
            - { label: Label, name: label, widget: string }
            - { label: URL, name: url, widget: string }
    - label: Footer
      file: src/content/data/footer.md
      name: footer
      fields:
        - label: Instagram Posts
          name: instagram
          widget: list
          fields: [{ label: Title, name: title, widget: string }, { label: Image, name: image, widget: image }, { label: URL, name: url, widget: string }]